name: hello-world
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
jobs:
  job1:
    name: test-node 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'    
    - run: npm i
    - run: npm run build --if-present
    - run: npm run test
  job2:
       needs: job1
       name: deploy to cluster
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@master
         name: build and push to docker
       - uses: docker/build-push-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: ${{ github.hello-world }}
           tag_with_ref: true
           tag_with_sha: true
           tags: ${{ github.sha}}