name: hello-world
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
jobs:
  job1:
    name: test-node 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: capstone_project/hello-world/package-lock.json    
    - run: npm ci
      working-directory: capstone_project/hello-world
    - run: npm run build --if-present
      working-directory: capstone_project/hello-world
    - run: npm run test
      working-directory: capstone_project/hello-world
  job2:
       needs: job1
       name: deploy to cluster
       runs-on: ubuntu-latest
       
       steps:
         -
           name: Set up QEMU
           uses: docker/setup-qemu-action@v1
         -
           name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1
         -
           name: Login to DockerHub
           uses: docker/login-action@v1 
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
         -
           name: Build and push
           uses: docker/build-push-action@v2
           with:
             fiel: capstone_project/hello-world
             container_name: hello-world
             push: true
             tags: user/app:latest
