name: hello-world
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
jobs:
  job1:
    name: test-node 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: capstone_project/hello-world/package-lock.json    
    - run: npm ci
      working-directory: capstone_project/hello-world
    - run: npm run build --if-present
      working-directory: capstone_project/hello-world
    - run: npm run test
      working-directory: capstone_project/hello-world
  job2:
       needs: job1
       name: deploy to cluster
       runs-on: ubuntu-latest
       
       steps:
         - uses: actions/checkout@v1
         - name: Docker login bill
           run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
         - name: Build
           run: docker build -t hello-world .
         - name: Tags
           run: |
            docker tag hello-world ${{ secrets.DOCKER_USER }}/hello-world:${{ github.sha }}
            docker tag hello-world ${{ secrets.DOCKER_USER }}/hello-world:latest
         - name: Push
           run: |
            docker push ${{ secrets.DOCKER_USER }}/hello-world:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USER }}/hello-world:latest
